import{a as y,S as h,i as n}from"./assets/vendor-BLPZKqeQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const L="50661011-0ce0d2a716009781924e103de",b="https://pixabay.com/api/",w=15;async function v(t,o=1){const r={key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:w};return(await y.get(b,{params:r})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".load-more"),m=document.querySelector(".loader"),P=new h(".gallery a",{captionsData:"alt",captionDelay:250});function S(t){const o=t.map(r=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${r.largeImageURL}">
        <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <ul class="meta">
        <li>Likes: <span>${r.likes}</span></li>
        <li>Views: <span>${r.views}</span></li>
        <li>Comments: <span>${r.comments}</span></li>
        <li>Downloads: <span>${r.downloads}</span></li>
      </ul>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",o),P.refresh()}function q(){d.innerHTML=""}function R(){m.classList.add("visible")}function B(){m.classList.remove("visible")}function M(){f.classList.remove("hidden")}function c(){f.classList.add("hidden")}const $=document.querySelector("form"),C=document.querySelector(".load-more");let p="",s=1,u=0;$.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.query.value.trim();if(!o){n.error({message:"Please enter a search term.",position:"topRight",backgroundColor:"#ef4040"});return}p=o,s=1,q(),c(),await g()});C.addEventListener("click",async()=>{s+=1,await g()});async function g(){R();try{const t=await v(p,s);if(t.hits.length===0){c(),n.info({message:"No images found. Try a different search.",position:"topRight",backgroundColor:"#ef4040"});return}if(S(t.hits),u=Math.ceil(t.totalHits/15),s>=u?(c(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040"})):M(),s>1){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#ef4040"})}finally{B()}}
//# sourceMappingURL=index.js.map
